url: https://respeaker.github.io
baseurl:

# Site settings
title: ReSpeaker
email:
description: "ReSpeaker is an open modular voice interface to hack things around you. Let you interact with your home appliances, your plant, your office, your internet-equipped devices or any other things in your daily life, all by your voice."
company: Seeedstudio

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/seeedstudio
  - title: facebook
    url: https://www.facebook.com/seeedstudiosz
  - title: github
    url: http://github.com/respeaker

# Build settings
highlighter: true
markdown: kramdown
permalink: pretty
